# Generated by Django 5.0.4 on 2024-05-07 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_buldings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="building",
            old_name="coordinates",
            new_name="geom",
        ),
    ]
