# Generated by Django 5.0.4 on 2024-05-13 16:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_buldings", "0002_rename_coordinates_building_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="geom",
            field=django.contrib.gis.db.models.fields.PolygonField(
                geography=True, srid=4326
            ),
        ),
    ]
